# -*- coding: utf-8 -*-
"""precipitation_model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvDB8Z-6yxawH1eLLv6_-ox4taGvt9we

# WaterWise — Accumulated Precipitation Prediction Model
**Feature:** Predict monthly accumulated precipitation (inches) for California CDEC stations.

**Inputs from frontend:** `station_id` (mapped from lat/lon), `month`, `year`  
**Output:** Predicted accumulated precipitation in inches  
**Data source:** CDEC Sensor 2 (Precipitation Accumulated), monthly, 2000–2025  

---
"""

import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (12, 5)
print("Libraries loaded.")

"""## 1. Load & Clean Data"""

# UPDATE THIS PATH for your environment
CSV_PATH = "Percipitation_Accumulated_predicition_-_Sheet1__2_.csv"  # Upload this file to Colab or update path
# If running in Colab, upload the file first or mount Google Drive

df = pd.read_csv(CSV_PATH, encoding="utf-8")
df.columns = df.columns.str.strip()

# Clean VALUE column
df["VALUE"] = df["VALUE"].astype(str).str.replace(",", "", regex=False).str.strip()
df["VALUE"] = pd.to_numeric(df["VALUE"], errors="coerce")

# Parse datetime
df["DATE TIME"] = pd.to_datetime(df["DATE TIME"], errors="coerce")

# Drop missing
df = df.dropna(subset=["VALUE", "DATE TIME"])

# Extract month and year
df["month"] = df["DATE TIME"].dt.month
df["year"] = df["DATE TIME"].dt.year

print(f"Total rows: {len(df)}")
print(f"Stations: {sorted(df['STATION_ID'].unique())}")
print(f"Date range: {df['DATE TIME'].min().date()} to {df['DATE TIME'].max().date()}")
print(f"\nValue stats (inches):")
print(df["VALUE"].describe().round(2))

"""## 2. Exploratory Data Analysis"""

# Monthly precipitation by station — seasonal pattern
fig, axes = plt.subplots(2, 3, figsize=(16, 10), sharey=False)
axes = axes.flatten()

for i, station in enumerate(sorted(df["STATION_ID"].unique())):
    ax = axes[i]
    s = df[df["STATION_ID"] == station]
    monthly = s.groupby("month")["VALUE"].agg(["mean", "std", "min", "max"])

    ax.fill_between(monthly.index, monthly["min"], monthly["max"], alpha=0.15, color="steelblue")
    ax.fill_between(monthly.index,
                    monthly["mean"] - monthly["std"],
                    monthly["mean"] + monthly["std"],
                    alpha=0.3, color="steelblue")
    ax.plot(monthly.index, monthly["mean"], "o-", color="steelblue", linewidth=2)
    ax.set_title(f"{station}", fontsize=13, fontweight="bold")
    ax.set_xlabel("Month")
    ax.set_ylabel("Precip (inches)")
    ax.set_xticks(range(1, 13))

# Hide extra subplot if odd number of stations
for j in range(i + 1, len(axes)):
    axes[j].set_visible(False)

plt.suptitle("Monthly Precipitation Patterns by Station\n(mean ± std, shaded = min/max range)",
             fontsize=15, fontweight="bold", y=1.02)
plt.tight_layout()
plt.show()

# Yearly total precipitation trends
fig, ax = plt.subplots(figsize=(14, 5))

for station in sorted(df["STATION_ID"].unique()):
    s = df[df["STATION_ID"] == station]
    yearly = s.groupby("year")["VALUE"].sum()
    ax.plot(yearly.index, yearly.values, "o-", label=station, linewidth=1.5, markersize=4)

ax.set_xlabel("Year", fontsize=12)
ax.set_ylabel("Total Annual Precipitation (inches)", fontsize=12)
ax.set_title("Annual Precipitation Totals by Station (2000–2025)", fontsize=14, fontweight="bold")
ax.legend(ncol=3, fontsize=10)
plt.tight_layout()
plt.show()

"""## 3. Feature Engineering

Since the model only receives **station + month + year** from the frontend, features are built from historical statistical profiles and trend analysis. No lag features (we won't have "last month's value" for future predictions).

"""

# Historical stats per station+month
station_month_stats = df.groupby(["STATION_ID", "month"])["VALUE"].agg(
    hist_mean="mean",
    hist_median="median",
    hist_std="std",
    hist_min="min",
    hist_max="max",
).reset_index()

# Per-station overall stats
station_stats = df.groupby("STATION_ID")["VALUE"].agg(
    station_mean="mean",
    station_max="max",
).reset_index()

# Yearly trend per station (linear slope of annual total precipitation)
yearly_totals = df.groupby(["STATION_ID", "year"])["VALUE"].sum().reset_index()
yearly_totals.columns = ["STATION_ID", "year", "yearly_total"]

station_trends = {}
for station in df["STATION_ID"].unique():
    s = yearly_totals[yearly_totals["STATION_ID"] == station]
    if len(s) > 2:
        coeffs = np.polyfit(s["year"], s["yearly_total"], 1)
        station_trends[station] = coeffs[0]
    else:
        station_trends[station] = 0.0

trend_df = pd.DataFrame(list(station_trends.items()), columns=["STATION_ID", "yearly_trend"])

print("Yearly precipitation trends (inches/year):")
for _, row in trend_df.iterrows():
    direction = "drying" if row["yearly_trend"] < 0 else "wetting"
    print(f"  {row['STATION_ID']}: {row['yearly_trend']:>+.3f} in/year ({direction})")

# Merge all features into main dataframe
df = df.merge(station_month_stats, on=["STATION_ID", "month"], how="left")
df = df.merge(station_stats, on=["STATION_ID"], how="left")
df = df.merge(trend_df, on=["STATION_ID"], how="left")

# Encode station as integer
station_map = {s: i for i, s in enumerate(sorted(df["STATION_ID"].unique()))}
df["station_encoded"] = df["STATION_ID"].map(station_map)

# Year offset
base_year = df["year"].min()
df["year_offset"] = df["year"] - base_year

# Cyclical month encoding
df["month_sin"] = np.sin(2 * np.pi * df["month"] / 12)
df["month_cos"] = np.cos(2 * np.pi * df["month"] / 12)

# Trend projection for this station+month
df["trend_projection"] = df["hist_mean"] + (df["year_offset"] * df["yearly_trend"] / 12)

# Coefficient of variation (how variable is precip at this station+month)
df["hist_cv"] = df["hist_std"] / (df["hist_mean"] + 0.01)  # avoid div by zero

# Feature columns
feature_cols = [
    "station_encoded",
    "month",
    "year_offset",
    "month_sin",
    "month_cos",
    "hist_mean",
    "hist_median",
    "hist_std",
    "hist_min",
    "hist_max",
    "station_mean",
    "station_max",
    "yearly_trend",
    "trend_projection",
    "hist_cv",
]

X = df[feature_cols]
y = df["VALUE"]

print(f"Feature matrix shape: {X.shape}")
print(f"Target stats: mean={y.mean():.2f}, std={y.std():.2f}, min={y.min():.2f}, max={y.max():.2f}")

"""## 4. Model Training & Evaluation

**Strategy:** Hold out the last 2 years (2024–2025) for testing. Train on 2000–2023. This simulates how the model would perform predicting future values it hasn't seen.

"""

# Train/test split — temporal hold-out
max_year = df["year"].max()
split_year = max_year - 1

train_mask = df["year"] < split_year
test_mask = df["year"] >= split_year

X_train, X_test = X[train_mask], X[test_mask]
y_train, y_test = y[train_mask], y[test_mask]

print(f"Train: {X_train.shape[0]} rows ({df[train_mask]['year'].min()}–{df[train_mask]['year'].max()})")
print(f"Test:  {X_test.shape[0]} rows ({df[test_mask]['year'].min()}–{df[test_mask]['year'].max()})")

# Train evaluation model
eval_model = XGBRegressor(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=3,
    random_state=42,
    n_jobs=-1,
)
eval_model.fit(X_train, y_train)
y_pred = eval_model.predict(X_test)

# Clamp predictions to non-negative (can't have negative precipitation)
y_pred = np.maximum(y_pred, 0)

"""### 4a. Overall Performance Metrics"""

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)
mape_vals = np.abs((y_test - y_pred) / (y_test + 0.01)) * 100  # avoid div/0

print("=" * 50)
print("OVERALL PERFORMANCE METRICS (Hold-out: last 2 years)")
print("=" * 50)
print(f"  MAE  (Mean Absolute Error):    {mae:.2f} inches")
print(f"  RMSE (Root Mean Square Error): {rmse:.2f} inches")
print(f"  R²   (Coefficient of Determ.): {r2:.4f}")
print(f"  Median Abs Error:              {np.median(np.abs(y_test - y_pred)):.2f} inches")
print("=" * 50)

"""### 4b. Per-Station Performance"""

eval_df = df[test_mask].copy()
eval_df["predicted"] = y_pred
eval_df["error"] = eval_df["VALUE"] - eval_df["predicted"]
eval_df["abs_error"] = np.abs(eval_df["error"])

station_metrics = []
print(f"{'Station':<8} {'MAE':>8} {'RMSE':>8} {'R²':>8} {'Avg Precip':>12}")
print("-" * 50)

for station in sorted(eval_df["STATION_ID"].unique()):
    s = eval_df[eval_df["STATION_ID"] == station]
    s_mae = mean_absolute_error(s["VALUE"], s["predicted"])
    s_rmse = np.sqrt(mean_squared_error(s["VALUE"], s["predicted"]))
    s_r2 = r2_score(s["VALUE"], s["predicted"]) if len(s) > 1 else 0
    s_avg = s["VALUE"].mean()

    station_metrics.append({
        "station": station, "mae": s_mae, "rmse": s_rmse, "r2": s_r2, "avg": s_avg
    })
    print(f"  {station:<6} {s_mae:>7.2f}  {s_rmse:>7.2f}  {s_r2:>7.3f}  {s_avg:>10.2f} in")

print()
avg_r2 = np.mean([m["r2"] for m in station_metrics])
print(f"Average R² across stations: {avg_r2:.3f}")

"""### 4c. Performance Visualizations"""

# Actual vs Predicted scatter
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Scatter plot
ax = axes[0]
for station in sorted(eval_df["STATION_ID"].unique()):
    s = eval_df[eval_df["STATION_ID"] == station]
    ax.scatter(s["VALUE"], s["predicted"], alpha=0.6, s=40, label=station)

max_val = max(eval_df["VALUE"].max(), eval_df["predicted"].max()) * 1.1
ax.plot([0, max_val], [0, max_val], "k--", linewidth=1, label="Perfect prediction")
ax.set_xlabel("Actual Precipitation (inches)", fontsize=11)
ax.set_ylabel("Predicted Precipitation (inches)", fontsize=11)
ax.set_title("Actual vs Predicted", fontsize=13, fontweight="bold")
ax.legend(fontsize=9)

# Error distribution
ax = axes[1]
ax.hist(eval_df["error"], bins=30, edgecolor="black", alpha=0.7, color="steelblue")
ax.axvline(0, color="red", linestyle="--", linewidth=1.5)
ax.set_xlabel("Prediction Error (inches)", fontsize=11)
ax.set_ylabel("Count", fontsize=11)
ax.set_title(f"Error Distribution (mean={eval_df['error'].mean():.2f})", fontsize=13, fontweight="bold")

plt.tight_layout()
plt.show()

# Per-station actual vs predicted over time
stations = sorted(eval_df["STATION_ID"].unique())
n_stations = len(stations)
fig, axes = plt.subplots(n_stations, 1, figsize=(14, 4 * n_stations), sharex=True)
if n_stations == 1:
    axes = [axes]

for ax, station in zip(axes, stations):
    s = eval_df[eval_df["STATION_ID"] == station].sort_values("DATE TIME")
    ax.plot(s["DATE TIME"], s["VALUE"], "o-", color="steelblue", label="Actual", linewidth=1.5)
    ax.plot(s["DATE TIME"], s["predicted"], "s--", color="coral", label="Predicted", linewidth=1.5)
    ax.fill_between(s["DATE TIME"], s["VALUE"], s["predicted"], alpha=0.15, color="red")
    ax.set_ylabel("Precip (in)")
    ax.set_title(f"{station} — Actual vs Predicted", fontweight="bold")
    ax.legend(loc="upper right")

plt.xlabel("Date")
plt.suptitle("Hold-out Period: Actual vs Predicted Precipitation", fontsize=14, fontweight="bold", y=1.01)
plt.tight_layout()
plt.show()

"""### 4d. Feature Importance"""

importances = eval_model.feature_importances_
feat_imp = pd.DataFrame({
    "feature": feature_cols,
    "importance": importances
}).sort_values("importance", ascending=True)

fig, ax = plt.subplots(figsize=(10, 6))
ax.barh(feat_imp["feature"], feat_imp["importance"], color="steelblue", edgecolor="black")
ax.set_xlabel("Importance", fontsize=12)
ax.set_title("Feature Importance (XGBoost)", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

"""### 4e. Cross-Validation Scores"""

# 5-fold CV on entire dataset for additional validation
cv_model = XGBRegressor(
    n_estimators=300, max_depth=5, learning_rate=0.05,
    subsample=0.8, colsample_bytree=0.8, min_child_weight=3,
    random_state=42, n_jobs=-1,
)

cv_r2 = cross_val_score(cv_model, X, y, cv=5, scoring="r2")
cv_mae = -cross_val_score(cv_model, X, y, cv=5, scoring="neg_mean_absolute_error")

print("5-Fold Cross-Validation Results:")
print(f"  R² scores:  {cv_r2.round(3)}")
print(f"  R² mean:    {cv_r2.mean():.3f} ± {cv_r2.std():.3f}")
print(f"  MAE scores: {cv_mae.round(3)}")
print(f"  MAE mean:   {cv_mae.mean():.3f} ± {cv_mae.std():.3f} inches")

"""## 5. Train Final Model & Export Pickle

Train on **all data** (2000–2025) for the production model, then save as pickle for the backend.

"""

# Train final model on ALL data
final_model = XGBRegressor(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=3,
    random_state=42,
    n_jobs=-1,
)
final_model.fit(X, y)

# Bundle everything the backend needs
model_bundle = {
    "model": final_model,
    "feature_cols": feature_cols,
    "station_map": station_map,
    "station_month_stats": station_month_stats,
    "station_stats": station_stats,
    "trend_df": trend_df,
    "base_year": base_year,
}

PICKLE_PATH = "precipitation_model.pkl"
with open(PICKLE_PATH, "wb") as f:
    pickle.dump(model_bundle, f)

print(f"Model saved to: {PICKLE_PATH}")
print(f"Stations: {list(station_map.keys())}")
print(f"Base year: {base_year}")

"""## 6. Backend Prediction Function

This is what your backend calls. Takes `station_id`, `month`, `year` and returns predicted precipitation in inches.

"""

def predict_precipitation(station_id: str, month: int, year: int, bundle: dict) -> float:
    """
    Predict accumulated precipitation for a given station, month, and year.

    Inputs (from frontend via backend):
        station_id: 3-letter CDEC code (e.g. "SHA")
        month: 1-12
        year: e.g. 2027

    Returns:
        Predicted precipitation in inches
    """
    sm_stats = bundle["station_month_stats"]
    s_stats = bundle["station_stats"]
    trends = bundle["trend_df"]
    s_map = bundle["station_map"]
    base_yr = bundle["base_year"]

    sm = sm_stats[(sm_stats["STATION_ID"] == station_id) & (sm_stats["month"] == month)]
    ss = s_stats[s_stats["STATION_ID"] == station_id]
    tr = trends[trends["STATION_ID"] == station_id]

    hist_mean = sm["hist_mean"].values[0]
    hist_median = sm["hist_median"].values[0]
    hist_std = sm["hist_std"].values[0]
    hist_min = sm["hist_min"].values[0]
    hist_max = sm["hist_max"].values[0]
    station_mean = ss["station_mean"].values[0]
    station_max = ss["station_max"].values[0]
    yearly_trend = tr["yearly_trend"].values[0]

    year_offset = year - base_yr
    month_sin = np.sin(2 * np.pi * month / 12)
    month_cos = np.cos(2 * np.pi * month / 12)
    trend_projection = hist_mean + (year_offset * yearly_trend / 12)
    hist_cv = hist_std / (hist_mean + 0.01)

    features = pd.DataFrame([{
        "station_encoded": s_map[station_id],
        "month": month,
        "year_offset": year_offset,
        "month_sin": month_sin,
        "month_cos": month_cos,
        "hist_mean": hist_mean,
        "hist_median": hist_median,
        "hist_std": hist_std,
        "hist_min": hist_min,
        "hist_max": hist_max,
        "station_mean": station_mean,
        "station_max": station_max,
        "yearly_trend": yearly_trend,
        "trend_projection": trend_projection,
        "hist_cv": hist_cv,
    }])

    prediction = bundle["model"].predict(features)[0]
    return max(0.0, round(prediction, 2))


# ── Demo predictions ──
print("DEMO PREDICTIONS")
print("=" * 65)

demos = [
    ("SHA", 1, 2027, "Shasta — Jan 2027 (wet season)"),
    ("SHA", 7, 2027, "Shasta — Jul 2027 (dry season)"),
    ("SHA", 12, 2020, "Shasta — Dec 2020 (drought year)"),
    ("CCH", 2, 2027, "Cachuma — Feb 2027 (wet season)"),
    ("CCH", 8, 2027, "Cachuma — Aug 2027 (dry season)"),
    ("TRM", 3, 2028, "Trinity — Mar 2028"),
    ("PNF", 1, 2028, "Pine Flat — Jan 2028"),
    ("MIL", 11, 2027, "Millerton — Nov 2027"),
    ("EXC", 4, 2027, "Exchequer — Apr 2027"),
]

for station, month, year, label in demos:
    pred = predict_precipitation(station, month, year, model_bundle)
    print(f"  {label}: {pred:.2f} inches")

"""## Summary

| Metric | Value |
|--------|-------|
| Model | XGBoost Regressor |
| Stations | 6 (SHA, TRM, PNF, EXC, CCH, MIL) |
| Training data | Monthly, 2000–2025 (~1,870 rows) |
| Features | 15 (station encoding, temporal, historical stats, trends) |
| Hold-out test | Last 2 years |
| Pickle file | `precipitation_model.pkl` |

**Backend usage:**
```python
import pickle, numpy as np, pandas as pd

with open("precipitation_model.pkl", "rb") as f:
    bundle = pickle.load(f)

result = predict_precipitation("SHA", 1, 2027, bundle)
# returns: predicted inches of precipitation
```

"""